name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        if: ${{ steps.release.outputs.release_created }}

      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: 22.x

      - name: Build
        run: npm ci
        if: ${{ steps.release.outputs.release_created }}

      - name: Publish to visual studio marketplace
        if: ${{ steps.release.outputs.release_created }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: npx vsce publish

      - name: Publish to open vsx
        if: ${{ steps.release.outputs.release_created }}
        run: npx ovsx publish -p ${{ secrets.OPEN_VSX_PAT }}

